spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/giveaway
    username: giveaway
    password: giveawayPassword
    driver-class-name: com.mysql.cj.jdbc.Driver
app:
  websocket:
    allowed-origins: http://localhost:3000
    destinations:
      notifications: "/topic/notification"
      giveaway: "/topic/giveaways"
      giveaway-collected: "/topic/giveaways/collected"
      balance-updated: "/topic/account/balance-updated"
      subscribed: "/topic/account/subscribed"
      unsubscribed: "/topic/account/unsubscribed"
jwt-auth:
  jwt:
    issuer: giveaway-chat
  http:
    unauthenticated-servlets:
      - "/auth/**"
      - "placeholder"